### ISSUE TITLE
Typo in import_export.py

### ISSUE THREAD

**Issue by ripplecurrent** [vizoogmbh/U3M-Blender-Add-on#1]
https://github.com/vizoogmbh/U3M-Blender-Add-on/blob/b2a3318dff649b2f5a8fe5f9a00994e1ca9f9a3a/import_export_U3M/import_export.py#L88

u3m_mat.front.basecolor.**textue.**image.width should be u3m_mat.front.basecolor.**texture.**image.width

Thanks.  Nice plugin btw.

**Comment by PatrickOnVizoo3d** [comment]
fixed with 1.0.1
