### ISSUE TITLE
Any chance an update for blender 4

### ISSUE THREAD

**Issue by eyedear** [vizoogmbh/U3M-Blender-Add-on#10]
Currently plug-in does not work in blender 4. Any change there would be an update to allow the plug in to work in blender 4

**Comment by FlorianVizoo3d** [comment]
Hi,
sorry for the long wait!
Good news: there will be an update to the addon. Probably shortly after the Blender 4.2 LTS release

**Comment by eyedear** [comment]
finally thanks

**Comment by eyedear** [comment]
Is it still plan the u3m plugin for blender

**Comment by FlorianVizoo3d** [comment]
Hi, the new version of this addon is currently in the testing phase and is expected to be released shortly. Thank you for staying tuned!
