### ISSUE TITLE
`.u3ma` Support

### ISSUE THREAD

**Issue by mathyouf** [vizoogmbh/U3M-Blender-Add-on#4]
Hello!

I would like to know if there is a possibility of adding support for the `.u3ma` binary format of `.u3m` files. Has this been considered?

**Comment by FlorianVizoo3d** [comment]
Hi,

thank you for your request!

We are currently looking into this and hope to also be able to support the import/export of U3MA format in a future version of this add-on. 

For the moment I'd like to suggest some possible workarounds for using U3MA files with this add-on:

1. Simply extract U3MA with a zip program (e.g. 7-Zip)
or
2. Uncompress U3MA with the [u3machecker.exe](https://github.com/vizoogmbh/u3m/tree/master/u3m1.1/utils) , which is a small Windows comand-line program to validate/compress/uncompress U3MA files.

After that you can load the .u3m file from the extracted folder. 

Note: If you want to bring your exported U3M back to U3MA format, you could also use the u3machecker
