### ISSUE TITLE
Windows path styles on Unix systems

### ISSUE THREAD

**Issue by aldebout** [vizoogmbh/U3M-Blender-Add-on#5]
Hi,

I'm rendering u3m files that come with Windows-style paths (`textures\\6274B_BASE.png`) on a Unix system.

It looks like the texture files are not found by the addon (I'm getting only the color, not the textures).

Are those paths OK from a spec standpoint? If that's the case, the addon should probably be fixed to accommodate them :)

**Comment by FlorianVizoo3d** [comment]
should be fixed in 1.1.0
